{% set name = "itrails" %}
{% set version = "2.0.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/trails-phylogeny/itrails/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9e978f6ebd2e68c36fc5a05ab70176652cb940a1c7e3920a64e898df28f33d58

build:
  noarch: python
  number: 0
  entry_points:
    - itrails-optimize = itrails.workflow_optimize:main
    - itrails-viterbi = itrails.workflow_viterbi:main
    - itrails-posterior = itrails.workflow_posterior:main
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4,<1.27
    - scipy >=1.13.0,<1.14
    - joblib >=1.4.2,<1.5
    - numba >=0.59.1,<0.60
    - biopython >=1.84,<1.85
    - pyyaml >=6.0.2,<6.1
    - h5py
    - ray-default

test:
  requires:
    - python {{ python_min }}
  imports:
    - itrails
  commands:
    - itrails-optimize --help
    - itrails-posterior --help
    - itrails-viterbi --help
    - itrails-int-optimize --help
    - itrails-int-viterbi --help
    - itrails-int-posterior --help

about:
  home: https://github.com/trails-phylogeny/itrails
  license: MIT
  license_file: LICENSE
  summary: "Tree reconstruction of ancestry using incomplete lineage sorting"

extra:
  recipe-maintainers:
    - David-M-P
